server:
  port: 80
  
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: xiangjiao
    password: bunana
    virtual-host: /xiangjiao
    #publisher-confirms: true   #消息发送到转发器确认机制，是都确认回调
    #publisher-returns: true
  
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wanwan?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    
#mybatis 配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    - classpath:mybatis/user/**/*.xml
    

